owner: videovillage
repo: status

sites:
  - name: License Service
    url: $VVLICENSE_ENDPOINT
    assignees:
      - wilg
  - name: Website
    url: https://videovillage.com

status-website:
  cname: status.videovillage.com
  logoUrl: https://status.videovillage.com/videovillage-symbol.png
  themeUrl: https://status.videovillage.com/vv-theme.css
  favicon: https://status.videovillage.com/favicon.png
  name: Video Village Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: hi! This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://videovillage.com
    - title: License
      href: https://license.videovillage.com
  customHeadHtml: |
    <link rel="stylesheet" href="https://use.typekit.net/mdj0otj.css">

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: ""
