owner: videovillage
repo: status

sites:
  - name: License Service
    url: $VVLICENSE_ENDPOINT
    assignees:
      - wilg
  # - name: Wikipedia
  #   url: https://en.wikipedia.org
  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://status.videovillage.com/videovillage-1line-dark.png
  themeUrl: https://status.videovillage.com/vv-theme.css
  name: Video Village Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: hi! This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://videovillage.com
    - title: License
      href: https://license.videovillage.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
